apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ORDER_SERVICE_URL: "http://order-service:5001"
  PAYMENT_SERVICE_URL: "http://payment-service:5002"
  INVENTORY_SERVICE_URL: "http://inventory-service:5003"
  RABBITMQ_URL: "amqp://guest:guest@messaging:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi9wZWRpZG9z  # base64 encoded